# Generated by Django 3.2.13 on 2022-08-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAINAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='Agree',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='ConnectionStatus',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='firm',
            name='HowYouKnowUs',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
